### ISSUE TITLE
Setup the software on Iphone

### ISSUE THREAD

**Issue by gogojjh** [yukunzhao998/DataCapture#1]
1. Clone this Repo: ```git clone https://github.com/yukunzhao998/DataCapture```
2. Download ```Unity Hub``` from the App store
3. Download ```Unity``` from the ```Unity Hub```
4. Open ```Unity Hub``` and open the ```DataCapture``` project
    * File -> Building Setting -> IOS -> Build to a new folder called build
5. Open ```Xcode```
    * Product -> Destination -> Phone
    * Click ```Unity-Phone``` -> Signing & Capacilities -> Setup Identity -> Build
6. Downlaod data from your iPhone
    * Prepare a mac book
    * Open Xcode
    * Click ```Window``` -> ```Devices and Simulator``` -> ```DataCapture``` -> ```Download the package```
    * Right click ```package``` and check data

**Comment by yukunzhao998** [comment]
Thanks for your effective complementation on the setup. The documentation and program have been updated.
